name: Create JS version

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  create-js-file:
    name: Create JS version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Build JS file
        run: |
          npm install
          npm run lint
          npm run build

      - name: Move into a folder
        run: |
          mkdir -p folderName
          mv Overlimit.js folderName/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: folderName
          clean: true
          clean-exclude: README.md
